cols_to_string:
- state_code
- derived_msa-md
- county_code
- census_tract
- action_taken
- purchaser_type
- preapproval
- loan_type
- loan_purpose
- lien_status
- reverse_mortgage
- open-end_line_of_credit
- business_or_commercial_purpose
- negative_amortization
- interest_only_payment
- balloon_payment
- other_nonamortizing_features
- construction_method
- occupancy_type
- manufactured_home_secured_property_type
- manufactured_home_land_property_interest
- applicant_credit_score_type
- co-applicant_credit_score_type
- applicant_ethnicity-1
- applicant_ethnicity-1
- applicant_ethnicity-2
- applicant_ethnicity-3
- applicant_ethnicity-4
- applicant_ethnicity-5
- co-applicant_ethnicity-1
- co-applicant_ethnicity-2
- co-applicant_ethnicity-3
- co-applicant_ethnicity-4
- co-applicant_ethnicity-5
- applicant_ethnicity_observed
- co-applicant_ethnicity_observed
- applicant_race-1
- applicant_race-2
- applicant_race-3
- applicant_race-4
- applicant_race-5
- co-applicant_race-1
- co-applicant_race-2
- co-applicant_race-3
- co-applicant_race-4
- co-applicant_race-5
- applicant_race_observed
- co-applicant_race_observed
- applicant_sex
- co-applicant_sex
- applicant_sex_observed
- co-applicant_sex_observed
- applicant_age_above_62
- co-applicant_age_above_62
- submission_of_application
- initially_payable_to_institution
- aus-1
- aus-2
- aus-3
- aus-4
- aus-5
- denial_reason-1
- denial_reason-2
- denial_reason-3
- denial_reason-4

llm:
  max_retry: 2